# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  q1_joint:
    has_velocity_limits: true
    max_velocity: 6.9813170079773181
    has_acceleration_limits: false
    max_acceleration: 0
  q2_joint:
    has_velocity_limits: true
    max_velocity: 6.2831853071795862
    has_acceleration_limits: false
    max_acceleration: 0
  q3_joint:
    has_velocity_limits: true
    max_velocity: 6.9813170079773181
    has_acceleration_limits: false
    max_acceleration: 0
  q4_joint:
    has_velocity_limits: true
    max_velocity: 8.7266462599716483
    has_acceleration_limits: false
    max_acceleration: 0
  q5_joint:
    has_velocity_limits: true
    max_velocity: 8.7266462599716483
    has_acceleration_limits: false
    max_acceleration: 0
  q6_joint:
    has_velocity_limits: true
    max_velocity: 13.962634015954636
    has_acceleration_limits: false
    max_acceleration: 0